---
abstract: 'Set and jump between named position markers on a filehandle'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  File::Temp: 0.14
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Marker
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  File::Marker:
    file: lib/File/Marker.pm
    version: 0.14
requires:
  Carp: 0
  IO::File: 0
  Scalar::Util: 1.09
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/File-Marker/issues
  homepage: https://github.com/dagolden/File-Marker
  repository: https://github.com/dagolden/File-Marker.git
version: 0.14
x_authority: cpan:DAGOLDEN
